services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
    volumes:
      - ./data/navidrome:/data
      - ./music:/music
    labels:
      - homepage.group=Media
      - homepage.name=Navidrome
      - homepage.url=http://pc:4533
      - homepage.description=Navidrome is a web-based music collection server and streamer
      - homepage.features=Music streaming, Web-based interface, Mobile support, Metadata management, Playlist creation
    networks:
      - MusicNet

  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    restart: unless-stopped
    ports:
      - "5030:5030"
      - "5031:5031"
    volumes:
      - ./data/slskd:/app
      - ./downloads:/downloads
      - ./music:/music
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SLSK_USERNAME=${SLSKD_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SLSKD_PASSWORD}
      - SLSKD_DOWNLOADS_DIR=/downloads
      - SLSKD_SHARED_DIR=/music
    labels:
      - homepage.group=Media
      - homepage.name=slskd
      - homepage.url=http://pc:5030/searches
      - homepage.description=slskd is a file sharing client for the Soulseek network, ingests music to the navidrome library.
      - homepage.features=File sharing, Soulseek client, Music downloading, Command-line interface
    networks:
      - MusicNet
  beets:
    image: linuxserver/beets:latest
    container_name: beets
    restart: unless-stopped
    volumes:
      - ./config/beets:/config
      - ./downloads:/downloads
      - ./music:/music
    environment:
      - PUID=1000
      - PGID=1000
    command: >
      sh -c "
      while true; do
        echo 'Checking for new music...' &&
        BEETSDIR=/config beet -vvv import /downloads;
        sleep 60;
      done
      "
    labels:
      - homepage.group=Media
      - homepage.name=Beets
      - homepage.url=https://beets.io/
      - homepage.description=Beets is a media library management system for music files. It catalogs your collection, automatically improving its metadata as it goes.
      - homepage.features=Library management, Metadata tagging, Music organization, Command-line interface, Plugin
      
networks:
  MusicNet: